---
all:
  children:

    durcies:            # groupe de groupes : les trois machines
      children:
        controle:
        applicatif:
        supervision:

    controle:
      hosts:
        bastion:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3

    applicatif:
      hosts:
        app:

    supervision:
      hosts:
        monitor:

  vars:
    ansible_user: ubuntu
